export const MYPROFILE_REQUEST = 'MYPROFILE_REQUEST'
export const MYPROFILE_SUCCESS = 'MYPROFILE_SUCCESS'
export const MYPROFILE_FAIL = 'MYPROFILE_FAIL'


export const MYPROFILE_GET_REQUEST = 'MYPROFILE_GET_REQUEST'
export const MYPROFILE_GET_SUCCESS = 'MYPROFILE_GET_SUCCESS'
export const MYPROFILE_GET_FAIL = 'MYPROFILE_GET_FAIL'